### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by dwt** [dataflake/Products.LDAPUserFolder#5]
Hi there,

as I'm currently starting to deploy this on some servers, I've found that I have to go to the master branch to get somewhat working py3 compatibility.

Are there some open tasks left for py3 compatibility that I could help with? Other than that, would it perhaps make sense to cut a release?

Thanks in any case for the feedback!

**Comment by dataflake** [comment]
Sorry that I have to say it that way, but.... you're joking, right?

As far as I can see from the commit history I had merged in a PR from you guys that was supposed to bring Python 3 compatibility. Unfortunately that left the master branch a complete mess. Just look at the Travis CI output. Then I got PR #4  that was supposed to fix the tests, but apart from some unwelcome cosmetic changes it appeared to just comment out failing tests. I had provided a review and had not heard back at all. So no, there's nothing that is even close to release-ready here.

**Comment by dataflake** [comment]
P.S.: And from the sound of your message you're using `master` in production? That's insane.

**Comment by dwt** [comment]
Uhm - I was under the impression all of this was dealt with. In lack of a stronger word, damn.

I'll see what I can pick up / make happen.

I am currently trying to get deployment together that allows testing on python3 - so not production yet but proving it out.

**Comment by dataflake** [comment]
This is now obsolete, a fixed version has been released.

**Comment by dwt** [comment]
Great to hear! Thanks for the great work!
