### ISSUE TITLE
Manage ldap.UNAVAILABLE exception in LDAPDelegate.connect

### ISSUE THREAD

**Issue by gbastien** [dataflake/Products.LDAPUserFolder#8]
Hi @dataflake 
we have a usecase here (AD Azure) where the LDAP returns a ldap.UNAVAILABLE exception, as discribed here: https://www.python-ldap.org/en/python-ldap-3.3.0/reference/ldap.html#ldap.UNAVAILABLE
As I can understand, this means that it could connect but the DSA (directory system agent) on the windows server is not ready.
We are still using the branch 2.x for this package, I will propose a PR then if it looks correct to you, it could be done in master as well.
Thank you in advance for review,
Gauthier

**Comment by dataflake** [comment]
I will take a look next week. I am traveling right now.

**Comment by dataflake** [comment]
Like I said in #9, I am not accepting any changes to the 2.x branch anymore. It is unsupported and unmaintained.

**Comment by gbastien** [comment]
Hi @dataflake 
ok we have a local release here for branch 2.x so "no problem", what about adding this change to the "master" branch?
We are using this on Zope2/Plone4 but we will move this application to Zope5/Plone6 soon and we will probably need this as well in last versions of Products.LDAPUserFolder if we do not move to another LDAP package.
Is this relevant?
Thank you for review,
Gauthier

**Comment by dataflake** [comment]
I have merged the change into `master` and have released version 5.1.
